<?php
require_once($_SERVER['DOCUMENT_ROOT']."/includes/config.php");
require_once(LIB_PATH."log.php");
require_once(LIB_PATH."file.php");
require_once(LIB_PATH."database.php");
require_once(LIB_PATH."databaseObject.php");
require_once(LIB_PATH."user.php");
require_once(LIB_PATH."partner.php");
require_once(LIB_PATH."ngo.php");
require_once(LIB_PATH."volunteer.php");
require_once(LIB_PATH."corporate.php");
require_once(LIB_PATH."cause.php");
require_once(LIB_PATH."project.php");
require_once(LIB_PATH."article.php");
require_once(LIB_PATH."session.php");
require_once(LIB_PATH."ngoSession.php");
require_once(LIB_PATH."volSession.php");
require_once(LIB_PATH."corpSession.php");
require_once(LIB_PATH."functions.php");
?>